name: Deploy DocC Documentation to Github Pages
on:
  # Runs on pushes targeting the master branch
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  SCHEME: SYButton

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # One deployment deploy job since we're just deploying
  deploy:
    environment:
      # Must set to this for deploying to GitHub Pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Select Xcode 16.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.1.0"
      - name: Verify Swift Version
        run: swift --version

      - name: Build DocC
        run: |
          swift package resolve;

          xcodebuild docbuild -scheme $SCHEME -derivedDataPath /tmp/docbuild -destination 'generic/platform=iOS';

          echo "Archiving documentation..."
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/$SCHEME.doccarchive \
            --output-path docs \
            --hosting-base-path ${SCHEME};
            
          echo "** Archived documentation**"

          # Define the lowercase version of SCHEME
          lowerCaseScheme=$(echo $SCHEME | tr '[:upper:]' '[:lower:]')

          # Use the lowercase variable in the redirect script
          echo "<script>window.location.href += \"/documentation/${lowerCaseScheme}\"</script>" > docs/index.html;

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload only docs directory
          path: "docs"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
